Issue 136.chia
Senzing/aws-cloudformation-ecs-poc-simple pull request #161
Opened 2021-11-08 16:46 UTC by mahchiahui

# Pull request questions

## Which issue does this address

Issue number: #136 

## Why was change needed

Needed authentication functionality in HTTP API gateway and Websocket API gateway

2021-11-08 17:19 UTC, docktermj commented on README.md
> +
On this one,  I think  having individual `exports` might be less confusing.  Example:

```console
export AWS_COGNITO_USERNAME="<replace-with-username>"
export AWS_COGNITO_PASSWORD="<replace-with-password>"
export AWS_COGNITO_CLIENT_ID="<replace-with-appclient-id>"
export AWS_COGNITO_POOL_ID="<replace-with-userpool-id>"
export API_URL="<replace-with-api-url>"
export AWS_REGION="<replace-with-aws-region>"
```

2021-11-11 02:15 UTC, roncewind requested changes
Hey Chia,  the convention that Mike set up in the CFTs is for the resource type to be the last line for the resource.  I think it would be a good idea if we continued to follow that convention.  Thanks!

2021-11-11 02:15 UTC, roncewind commented on cloudformation.yaml
> +    Condition: IfUsingWeb
Is this right?  I don't recall the semantics around IfUsingApiServer versus IfUsingWeb.

2021-11-11 19:18 UTC, mahchiahui commented on README.md
> +
done

2021-11-11 19:21 UTC, mahchiahui commented on cloudformation.yaml
> +    Condition: IfUsingWeb
hmm should i switch all ifusingapiserver to ifusingweb?

I just looked through and ifusingweb encompasses more conditions

```
IfUsingApiServer: !Or
    - !Condition IfRunApiServer
    - !Condition IfRunSwagger
    - !Condition IfRunWebApp
 
IfUsingWeb: !Or
    - !Condition IfRunApiServer
    - !Condition IfRunJupyter
    - !Condition IfRunSwagger
    - !Condition IfRunWebApp
    - !Condition IfRunXterm
```

2021-11-12 16:27 UTC, roncewind commented on cloudformation.yaml
> +    Condition: IfUsingWeb
Seems like you only need the API server for the WebSocket interface?  Hm... also of note is that only the POC server has websockets (I believe), so we should probably make a note of that somewhere.  so much to do.  :-)

2021-11-13 08:25 UTC, mahchiahui commented on cloudformation.yaml
> +    Condition: IfUsingWeb
hmmm should we then revamp the discussion some of the conditions?

2021-12-02 19:51 UTC, docktermj approved these changes

2021-12-14 18:06 UTC, closed without merging